#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use Getopt::Long;

my ( $dead_master_host, $new_master_host, $new_slave_hosts, $subject, $body );
GetOptions( 'orig_master_host=s' => \$dead_master_host,
                        'new_master_host=s'  => \$new_master_host,
                        'new_slave_hosts=s'  => \$new_slave_hosts,
                        'subject=s'          => \$subject,
                        'body=s'             => \$body,);
my $mail_title = "mha_$dead_master_host\_dead_$new_master_host\_up";
my $mail_body = "mysql_master_changed";
my $mail_to = '309707872@qq.com';
my $cmd_mail = "echo $mail_body\|mail -s $mail_title  $mail_to";
system($cmd_mail);

my $server1 = "192.168.1.3";
my $server2 = "192.168.1.4";
my $server3 = "192.168.1.5";
my $delete_host = "";
if($dead_master_host eq $server1){
   $delete_host = "server1"
}
if($dead_master_host eq $server2){
   $delete_host = "server2"
}
if($dead_master_host eq $server3){
   $delete_host = "server3"
}


my $delete_host_cmdline = "/usr/bin/masterha_conf_host --command=delete --conf=/opt/mha/mha.conf --block=$delete_host";
system($delete_host_cmdline);

my $restart_cmdline = "nohup /usr/bin/perl /usr/bin/masterha_manager --conf=/opt/mha/mha.conf & ";
system($restart_cmdline);

my $delete_complete_file_cmdline = "rm -rf /opt/mha/logs/mha_bin_log/mha.failover.complete";
system($delete_complete_file_cmdline);
exit 0;

